exec sp_rename 'AVIATOR_WORKFLOW.DELETED_BY', 'DELETED_BY__U31350', 'COLUMN' ^
exec sp_rename 'AVIATOR_WORKFLOW.DELETE_TS', 'DELETE_TS__U28702', 'COLUMN' ^
exec sp_rename 'AVIATOR_WORKFLOW.UPDATED_BY', 'UPDATED_BY__U39829', 'COLUMN' ^
exec sp_rename 'AVIATOR_WORKFLOW.UPDATE_TS', 'UPDATE_TS__U00294', 'COLUMN' ^
exec sp_rename 'AVIATOR_WORKFLOW.CREATED_BY', 'CREATED_BY__U13988', 'COLUMN' ^
exec sp_rename 'AVIATOR_WORKFLOW.CREATE_TS', 'CREATE_TS__U88652', 'COLUMN' ^
exec sp_rename 'AVIATOR_WORKFLOW.VERSION', 'VERSION__U60100', 'COLUMN' ^
alter table AVIATOR_WORKFLOW alter column VERSION__U60100 int  ;
