exec sp_rename 'AVIATOR_ACCOUNT.DELETED_BY', 'DELETED_BY__U17859', 'COLUMN' ^
exec sp_rename 'AVIATOR_ACCOUNT.DELETE_TS', 'DELETE_TS__U69684', 'COLUMN' ^
exec sp_rename 'AVIATOR_ACCOUNT.UPDATED_BY', 'UPDATED_BY__U19623', 'COLUMN' ^
exec sp_rename 'AVIATOR_ACCOUNT.UPDATE_TS', 'UPDATE_TS__U11424', 'COLUMN' ^
exec sp_rename 'AVIATOR_ACCOUNT.CREATED_BY', 'CREATED_BY__U57150', 'COLUMN' ^
exec sp_rename 'AVIATOR_ACCOUNT.CREATE_TS', 'CREATE_TS__U63111', 'COLUMN' ^
exec sp_rename 'AVIATOR_ACCOUNT.VERSION', 'VERSION__U75496', 'COLUMN' ^
alter table AVIATOR_ACCOUNT alter column VERSION__U75496 int  ;
